const CartActionTypes = {
	TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
	CART_ITEM_TO_REMOVE: 'CART_ITEM_TO_REMOVE',
	ADD_ITEM: 'ADD_ITEM',
	CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART"
}


export default CartActionTypes;