const PRODUCT_SLIDER = {
  products : [
    {
      id: 1,
      name: 'Accessories',
      category: 'Shirts',
      imageUrl: '/images/accessories.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 11,
			description: 'High Quality Slim Shirts',
    },
    {
      id: 2,
      name: 'Beauty Make-Up',
      category: 'Slim fit',
      imageUrl: '/images/face-make-up.jpg',
      price: 90,countInStock: 12,
      brand: 'Adidas',
      rating: '4.5',
      numReviews: 5,
      description: 'High Quality Slim fit',
    },
    {
      id: 3,
      name: 'Computers',
      category: 'Shirts',
      imageUrl: '/images/device.jpg',
      price: 65,
      brand: 'Gucci',
      countInStock: 0,
      rating: '4.5',
      numReviews: 20,
      description: 'Mens Wrist Warch Collections',
    },
    {
      id: 4,
      name: 'Skin Care Lotion',
      category: ' VersaceShirts',
      imageUrl: '/images/felge.jpg',
      price: 100,
      countInStock: 15,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 100,
      description: 'High Quality Slim Shirts',
    },
    {
      id: 5,
      name: 'Beauty Fragrance',
      category: 'Puma Shirts',
      imageUrl: '/images/fragrance.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Puma',
      rating: '4.5',
      numReviews: 8,
      description: 'High Quality Slim Shirts',
    },
    {
      id: 6,
      name: 'Shawarma',
      category: 'Pants',
      imageUrl: '/images/shawarma.jpg',
      price: 50,
      countInStock: 9,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 15,
      description: 'High Quality Slim Shirts',
    },
   
    {
      id: 7,
      name: 'Tablets',
      category: 'Shirts',
      imageUrl: '/images/tables.jpg',
      price: 150,
      countInStock: 25,
      brand: 'Zara',
      rating: '4.5',
      numReviews: 10,
			description: 'High Quality Zara Short Sleeve',
    },
    {
      id: 8,
      name: 'Vegetable Bugger',
      category: 'Shirts',
      imageUrl: '/images/vegetable-bugger.jpg',
      price: 35,
      countInStock: 13,
      brand: 'Zara',
      rating: '4.5',
      numReviews: 10,
			description: 'High Quality Zara Short Sleeve Shirts',
    },
    {
      id: 9,
      name: 'Skin Care Cream',
      category: 'Shirts',
      imageUrl: '/images/skin-care-cream.png',
      price: 100,
      countInStock: 10,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 11,
      description: 'High Quality Slim Shirts',
    },
    {
      id: 10,
      name: 'Mens Watch',
      category: 'Slim fit',
      imageUrl: '/images/mens_watch.jpg',
      price: 90,countInStock: 12,
      brand: 'Adidas',
      rating: '4.5',
      numReviews: 5,
      description: 'High Quality Slim fit',
    },
    {
      id: 11,
      name: 'Eye Make-Up',
      category: 'Shirts',
      imageUrl: '/images/eye-make-up.png',
      price: 65,
      brand: 'Gucci',
      countInStock: 0,
      rating: '4.5',
      numReviews: 20,
      description: 'Mens Wrist Warch Collections',
    },
    {
      id: 12,
      name: 'Computers',
      category: ' VersaceShirts',
      imageUrl: '/images/computers.jpg',
      price: 100,
      countInStock: 15,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 100,
      description: 'High Quality Slim Shirts',
    },
    {
      id: 13,
      name: 'Amqey Food',
      category: 'Puma Shirts',
      imageUrl: '/images/amqey-food-chips.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Puma',
      rating: '4.5',
      numReviews: 8,
      description: 'High Quality Slim Shirts',
    },
    {
      id: 14,
      name: 'Hair Oil',
      category: 'Pants',
      imageUrl: '/images/hair-oil.png',
      price: 50,
      countInStock: 9,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 15,
      description: 'High Quality Slim Shirts',
    },
    {
      id: 15,
      name: 'Sab Chicken',
      category: 'Shirts',
      imageUrl: '/images/fried-chicken.jpg',
      price: 150,
      countInStock: 25,
      brand: 'Zara',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Zara Short Sleeve',
    },
    {
      id: 16,
      name: 'Sun Bum',
      category: 'Shirts',
      imageUrl: '/images/sun-bum-shine.jpg',
      price: 35,
      countInStock: 13,
      brand: 'Zara',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Zara Short Sleeve Shirts',
    },
  ],
};

export default PRODUCT_SLIDER;