export const data = 
 [
    {
      _id: 1,
      name: 'Beauty Lotion',
      category: "Body lotion", 
      image: '/images/amqey-beauty.jpg',
      price: 2000,
      brand: 'Amqey',
      rating: '3.5',
      numReviews: 20,
      description: 'Beauty That Shines',
    },
    {
      _id: 2,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: '2000',
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 3,
      name: 'Shave Butter',
      category: "Body lotion",
      image: '/images/shave-butter.jpg',
      price: 1700,
      brand: 'Amqey',
      rating: '4.0',
      numReviews: 15,
      description: 'High Quality shave Butter',
    },
    {
      _id: 4,
      name: '',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: 1000,
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 5,
      name: 'Furniture',
      category: "Beds$funiture",
      image: '/images/beds&furniture.png',
      price: 1.500000,
      brand: 'Amqey furniture',
      rating: '4.5',
      numReviews: 50,
      description: 'High Comfort Furniture',
    },
    {
      _id: 6,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: 4999,
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 1000,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 7,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: 1400,
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 35,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 8,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: 1400,
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 25,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 9,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: '999',
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 15,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 10,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/images/sun-bum.jpg',
      price: 3000,
      brand: 'Amqey',
      rating: '4.0',
      numReviews: 10,
      description: 'High Quality Sun Bun',
    },
  ]

