export const data = 
 [
   {
     _id: 2,
     name: 'Sun Bum',
     category: "Body lotion",
     image: '/amqey-images/sun-bum-shine.jpg',
     price: 1400,
     brand: 'Amqey',
     rating: '4.5',
     numReviews: 35,
     description: 'High Quality Sun Bun',
    },
    {
      _id: 2,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/amqey-images/sun-bum-shine.jpg',
      price: '2000',
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Sun Bun',
    },
    {
    _id: 3,
    name: 'Furniture',
    category: "Beds$funiture",
    image: '/amqey-images/eye-make-up.png',
    price: 1.500000,
    brand: 'Amqey furniture',
    rating: '4.5',
    numReviews: 50,
    description: 'High Comfort Furniture',
    },
     {
      _id: 4,
      name: 'Furniture',
      category: "Lotion",
      image: '/amqey-images/skin-care.png',
      price: 1.500000,
      brand: 'Amqey furniture',
      rating: '4.5',
      numReviews: 50,
      description: 'High Comfort Furniture',
    },
    {
      _id: 5,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/amqey-images/sun-bum-shine.jpg',
      price: 1400,
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 25,
      description: 'High Quality Sun Bun',
    },
    {
      _id: 6,
      name: 'Sun Bum',
      category: "Body lotion",
      image: '/amqey-images/sun-bum-shine.jpg',
      price: '999',
      brand: 'Amqey',
      rating: '4.5',
      numReviews: 15,
      description: 'High Quality Sun Bun',
    },
    // {
    //   _id: 7,
    //   name: 'Sun Bum',
    //   category: "Body lotion",
    //   image: '/amqey-images/sun-bum-shine.jpg',
    //   price: 3000,
    //   brand: 'Amqey',
    //   rating: '4.0',
    //   numReviews: 10,
    //   description: 'High Quality Sun Bun',
    // },
    // {
    //   _id: 8,
    //   name: 'Sun Bum',
    //   category: "Body lotion",
    //   image: '/images/sun-bum-shine.jpg',
    //   price: 4999,
    //   brand: 'Amqey',
    //   rating: '4.5',
    //   numReviews: 1000,
    //   description: 'High Quality Sun Bun',
    // },
    //   {
    //   _id: 10,
    //   name: 'Fragrance Beauty',
    //   category: "Body lotion",
    //   image: '/amqey-images/fragrance.jpg',
    //   price: 1700,
    //   brand: 'Amqey',
    //   rating: '4.0',
    //   numReviews: 15,
    //   description: 'High Quality shave Butter',
    // },
    
    // {
    //   _id: 11,
    //   name: '',
    //   category: "Body lotion",
    //   image: '/amqey-images/bugger.jpg',
    //   price: 1000,
    //   brand: 'Amqey',
    //   rating: '4.5',
    //   numReviews: 10,
    //   description: 'High Quality Sun Bun',
    // },
   
    //  {
    //   _id: 12,
    //   name: 'Computers',
    //   category: "Computers", 
    //   image: '/amqey-images/tables.jpg',
    //   price: 2000,
    //   brand: 'Amqey',
    //   rating: '3.5',
    //   numReviews: 20,
    //   description: 'The Real HD',
    // },
    //  {
    //   _id: 12,
    //   name: 'vegetable bugger',
    //   category: "Food", 
    //   image: '/amqey-images/felge.jpg',
    //   price: 2000,
    //   brand: 'Amqey',
    //   rating: '3.5',
    //   numReviews: 20,
    //   description: 'Beauty That Shines',
    // },
    
    
  ]

